- name: create group msg
  become: yes
  group:
    name: msg-service
    state: present

- name: create user msg
  become: yes
  user:
    name: msg-service
    group: msg-service

- name: create folder conf
  file: path=/opt/msg-service/conf state=directory mode=0777 #owner=msg-service group=msg-service
  become: yes

- name: create folder bin
  file: path=/opt/msg-service/bin state=directory mode=0777 #owner=msg-service group=msg-service
  become: yes

- name: download msg-server
  get_url: url=https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/msg-service/msg-server dest="/opt/msg-service/bin" mode=0777
  become: yes

- name: copy conf config
  template:
    src: msg-service.config.j2
    dest: /opt/msg-service/conf/msg-service.conf

- name: copy unit
  copy: 
    src: msg-service.service
    dest: /etc/systemd/system/msg-service.service mode=0644 owner=root group=root

- name: enable application service
  service: name=msg-service enabled=yes

- name: start application service
  systemd:
    state: started
    name: msg-service.service
