---
# tasks file for base

- name: Create dir facts
  file: path=/etc/ansible/facts.d state=directory recurse=yes
  become: yes

- name: Install epel-release
  yum: name=epel-release
  become: yes

- name: Install other packages
  yum:
    name:
    - python-pip
    - pythom-devel
    - curl
  become: yes
    
